[package]
name = "nostd_tetris"
version = "0.1.0"
authors = [ "Petr Gadorek <hahihula@gmail.com>"]
edition = "2024"

[lib]
name = "tetris_game"
path = "src/lib.rs"

[[bin]]
name = "tetris"
path = "src/main.rs"

[dependencies]
crossterm = "0.27"
ctrlc = "3.4"